# SPDX-FileCopyrightText: Copyright Â© 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Run the equivalent of "apt-get clean" and "apt-get update".
  ansible.builtin.apt:
    clean: true
    update_cache: true
